---
title: Papa Pawsome
description: Ultra Pet care Products! Natural Paw Cream coz Cracked Paws Hurt! üêæ Mint & Basil extracts Mouth Freshner coz even we don't like bad mouth odour! üêï
logo: /images/papa_pawsome_logo.png
timezone: Asia/Kolkata
collections:
  testimonials:
    title: Testimonials
    output: false
  outlets:
    title: Outlets
    output: false
  uploads:
    title: Uploads
    output: false
  products:
    title: Products
    output: false
  posts:
    permalink: "/blog/:title/"
    output: true
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
url: https://www.papapawsome.com
permalink: pretty
social:
  links:
    - https://www.instagram.com/papapawsome/
    - https://www.facebook.com/papapawsome
google_site_verification: B6Q_EJrJgXsoJGJOqzhJLK7QcMwpOt9JhYzB4FVIeKQ
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
sass:
  sass_dir: styles/
  style: compressed
